### ISSUE TITLE
Folder name for 'Sanitized' report incorrect

### ISSUE THREAD

**Issue by BBhacKing** [clr2of8/DPAT#3]
## Expected Behavior
Passing a directory in -d and the -s arg to sanitize the report would put "Sanitized -" in front of the destination directory.

## Actual Behavior
A directory called "Sanitized - " is created in the current directory, and the dir tree I passed in is created underneath it.

### Example
`dpat.py -n customer.ntds -c cracked.txt -d ~/customer/artifacts/ -s`

Results in a folder called `./Sanitized - /home/tester/customer/artifacts/` with all the dpat.py output in it.

(I mean, that's what it _says_ it'll do, but I don't think that's what it _meant_ to do...)

## Suggested Solution:
This uses a different naming convention, but has the benefit of being a small change to the script.

Change line 29 of dpat.py from
`    folder_for_html_report = "Sanitized - " + folder_for_html_report`
to
`    folder_for_html_report = os.path.join(folder_for_html_report, "DPAT-Sanitized")`

## Sample Run

```
>>> import os
>>> folder_for_html_report = "~/customer/artifacts/"
>>> folder_for_html_report = os.path.join(folder_for_html_report, "DPAT-Sanitized")
>>> folder_for_html_report 
'~/customer/artifacts/DPAT-Sanitized'
```

**Comment by clr2of8** [comment]
Fixed via Pull Request 6 from Cameron Roberts by adding " - Sanitized" to the end of the folder path instead of the beginning.
