### ISSUE TITLE
Hex Encoded passwords in potfile

### ISSUE THREAD

**Issue by xillwillx** [clr2of8/DPAT#5]
Per our talk on Twitter, Hashcat hex encodes passwords that contain non-Ascii chars or a colon (since a colon is used as a delimiter between hash and password). DPAT grabs this hexed password char length and mistakenly adds the hex length versus that actual password length.
Something like this in the code can get the password characters converted and the total length. 

`
import binascii,re
hex ="$HEX[4be474746368656e]"
hex2 = (binascii.unhexlify(re.findall("\[([^[\]]*)\]", hex)[-1]))
print (len(hex2.decode("utf-8", "replace")))
l=list()
for x in list(hex2):
  l.append(chr(x))

"".join(l)
`

**Comment by clr2of8** [comment]
This issue was resolved in Pull 7 thanks to Cameron Roberts. Thank you for reporting this and for the sample code!
